version: '3.4'
services:
  albion-online-discord-bot-db:
    container_name: albion-online-discord-bot-db
    image: mysql:5.7
    env_file:
      - .env
    ports:
      - '3306:3306'
    volumes:
      - db-vol:/var/lib/mysql
    networks:
      - webnet
  albion-online-discord-bot:
    container_name: albion-online-discord-bot
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
    command: npm run start
    networks:
      - webnet
  phpmyadmin:
    container_name: albion-online-discord-bot-phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    links:
      - albion-online-discord-bot-db
    restart: always
    environment:
      PMA_HOST: albion-online-discord-bot-db
      PMA_PORT: '3306'
      PMA_ARBITRARY: '1'
    ports:
      - 8081:80
    networks:
      - webnet

networks:
  webnet:

volumes:
  db-vol: